CREATE TABLE CUSTOMERS(
  MONTH VARCHAR(20),
  DAYS INT NOT NULL
);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Январь', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Февраль', 28);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Март', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Апрель', 30);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Май', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Июнь', 30);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Июль', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Август', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Сентябрь', 30);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Октябрь', 31);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Ноябрь', 30);
INSERT INTO CUSTOMERS (MONTH,DAYS) VALUES ('Декабрь', 31);
